<?php

namespace EightyEight\SkyBundle\Entity;

/**
 * ConstellationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstellationRepository extends \Doctrine\ORM\EntityRepository
{
    public function delete()
    {
        return $this->createQueryBuilder("delete")
            ->delete()
            ->getQuery()
            ->execute();
    }
}
